services:
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./data/grafana:/var/lib/grafana
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./data/prometheus:/prometheus
      - ./prometheus:/etc/prometheus:ro
      - /etc/timezone:/etc/timezone:ro

  cloudflared:
    image: cloudflare/cloudflared:latest
    volumes:
      - /etc/timezone:/etc/timezone:ro
    command: tunnel run --token "{{ o11y_cloudflared_token }}"
    depends_on:
      - grafana
      - prometheus
    restart: always
