services:
  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./alertmanager/config.yaml:/etc/alertmanager/config.yaml:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./data/prometheus:/prometheus
      - ./prometheus:/etc/prometheus:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./data/grafana:/var/lib/grafana
      - /etc/timezone:/etc/timezone:ro
    restart: always
    depends_on:
      - prometheus

  cloudflared:
    image: cloudflare/cloudflared:latest
    volumes:
      - /etc/timezone:/etc/timezone:ro
    command: tunnel run --token "{{ o11y_cloudflared_token }}"
    restart: always
    depends_on:
      - prometheus
      - grafana
