global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "server"
    http_headers:
      CF-Access-Client-Id:
        values:
          - "47b2c772dac3a4d4ae409ec56f96d993.access"
      CF-Access-Client-Secret:
        secrets:
          - "{{ prom_client_secret_token }}"
    static_configs:
      - targets: ["prom-oci-obs-sv02.a-marsh.net"]
        labels:
          server_name: "oci-obs"
      - targets: ["prom-oci-rpx-sv02.a-marsh.net"]
        labels:
          server_name: "oci-rpx"
      - targets: ["prom-kagoya-dev-sv01.a-marsh.net"]
        labels:
          server_name: "kagoya-dev"
      - targets: ["prom-kagoya-mc-sv01.a-marsh.net"]
        labels:
          server_name: "kagoya-mc"
      - targets: ["prom-kagoya-mc-edion-sv01.a-marsh.net"]
        labels:
          server_name: "kagoya-mc-edion"
      - targets: ["prom-kagoya-pal-sv01.a-marsh.net"]
        labels:
          server_name: "kagoya-pal"
