---
- name: Kagoya - Apply netplan
  ansible.builtin.command: netplan apply
  become: true
  register: platform_kagoya_apply_netplan
  changed_when: true
  failed_when: platform_kagoya_apply_netplan.rc != 0
