---
- name: OCI - Apply iptables rules
  ansible.builtin.command: iptables-restore /etc/iptables/rules.v4
  become: true
  register: platform_oci_apply_iptables
  changed_when: true
  failed_when: platform_oci_apply_iptables.rc != 0
  notify: "OCI - Restart Docker"

- name: OCI - Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
  become: true
