services:
  app:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    stop_grace_period: 30s # Set to however long you are willing to wait for the container to gracefully stop
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
      - 8212:8212/tcp # Port for REST API if REST_API_ENABLED: true
    environment:
      TZ: "Asia/Tokyo"
      PUID: 1000
      PGID: 1000
      PORT: 8211 # Optional but recommended
      PLAYERS: 16 # Optional but recommended
      SERVER_PASSWORD: "{{ pal_server_password }}" # Optional but recommended
      MULTITHREADING: true
      RCON_ENABLED: true
      RCON_PORT: 25575
      ADMIN_PASSWORD: "{{ pal_admin_password }}"
      COMMUNITY: false # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
      REST_API_ENABLED: true
      SERVER_NAME: "{{ pal_join_fqdn }}"
      SERVER_DESCRIPTION: "Working!"
      ALLOW_CONNECT_PLATFORM: "Steam" # Defaults to "Steam" if not set, set this to "Xbox" if you want to host a server for Xbox players. CROSSPLAY BETWEEN XBOX-STEAM IS NOT YET SUPPORTED
      BASE_CAMP_MAX_NUM_IN_GUILD: 5
      BASE_CAMP_WORKER_MAX_NUM: 20
      PAL_EGG_DEFAULT_HATCHING_TIME: "1.000000"
      # Discord Webhook settings
      DISCORD_WEBHOOK_URL: "{{ pal_discord_webhook_url }}"
      DISCORD_PRE_UPDATE_BOOT_MESSAGE: "⛔ サーバーは停止しました (アップデート中)"
      DISCORD_POST_UPDATE_BOOT_MESSAGE: "✅ サーバーが起動しました (アップデート完了)"
      DISCORD_PRE_START_MESSAGE: "✅ サーバーが起動しました"
      DISCORD_PRE_SHUTDOWN_MESSAGE_ENABLED: false
      DISCORD_POST_SHUTDOWN_MESSAGE: "⛔ サーバーは停止しました"
      DISCORD_PLAYER_JOIN_MESSAGE: "player_name がサーバーに参加しました"
      DISCORD_PLAYER_LEAVE_MESSAGE: "player_name はサーバーから退出しました"
      DISCORD_PRE_BACKUP_MESSAGE_ENABLED: false
      DISCORD_POST_BACKUP_MESSAGE_ENABLED: false
      DISCORD_PRE_BACKUP_DELETE_MESSAGE_ENABLED: false
      DISCORD_POST_BACKUP_DELETE_MESSAGE_ENABLED: false
    volumes:
      - ./data/app:/palworld/
