services:
  app:
    image: quay.io/prometheus/node-exporter:v1.11.1
    command:
      - "--path.rootfs=/host"
      - "--collector.systemd"
    network_mode: host
    pid: host
    security_opt:
      - apparmor=unconfined
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
      - "/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro"
