# am-helper settings
---
- name: Am-helper - Install git
  ansible.builtin.apt:
    name: git
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Am-helper - Create directory
  ansible.builtin.file:
    path: "/opt/a-marsh"
    state: directory
    owner: "am-helper"
    group: "am-helper"
    mode: "0755"

- name: Am-helper - Clone am-helper
  ansible.builtin.git:
    repo: "https://github.com/AhiruMarsh/am-helper"
    dest: "/opt/a-marsh/am-helper"
    version: "main"
  become: true
  become_user: "root"
  ignore_errors: true
  notify: "Am-helper - Copy config"

- name: Am-helper - Set systemd service
  ansible.builtin.copy:
    src: "/opt/a-marsh/am-helper/systemd/{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - "am-helper.service"
    - "am-helper.timer"
  notify: "Am-helper - Reload systemd service"
