# cloudflared Settings

# vars example
# vars:
#   cloudflared_token: string
---
- name: cloudflared - Create directory
  file:
    path: "/etc/apt/keyrings"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  when: ansible_distribution == "Ubuntu"

- name: cloudflared - Add Docker's official GPG key
  get_url:
    url: https://pkg.cloudflare.com/cloudflare-main.gpg
    dest: /usr/share/keyrings/cloudflare-main.gpg
    owner: "root"
    group: "root"
    mode: "0644"
  when: ansible_distribution == "Ubuntu"

- name: cloudflared - Add the repository to Apt sources
  shell: |
    echo \
      "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared \
      jammy main" | \
      tee /etc/apt/sources.list.d/cloudflared.list > /dev/null
  register: cloudflared_apt_add_repo
  changed_when: false
  failed_when: cloudflared_apt_add_repo.rc != 0
  when: ansible_distribution == "Ubuntu"

- name: cloudflared - Update packages cache
  apt:
    update_cache: true
    state: present

- name: cloudflared - Install cloudflared
  apt:
    name: cloudflared
    state: present

- name: cloudflared - Set systemd service
  shell: cloudflared service install {{ cloudflared_token }}
  register: cloudflared_service
  changed_when: cloudflared_service.rc == 0
  failed_when: cloudflared_service.rc not in [0,1]
  when: cloudflared_token is defined
