# cockpit Settings
---
- name: Cockpit - Install cockpit
  ansible.builtin.apt:
    name:
      - cockpit
      - cockpit-pcp
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Cockpit - Set customized config
  ansible.builtin.template:
    src: "cockpit/cockpit.conf.j2"
    dest: "/etc/cockpit/cockpit.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "Cockpit - Set systemd service"

- name: Cockpit - Set network dummy config
  ansible.builtin.template:
    src: "cockpit/10-globally-managed-devices.conf"
    dest: "/etc/NetworkManager/conf.d/10-globally-managed-devices.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "Cockpit - Apply network dummy config"
