# cockpit Settings
---
- name: cockpit - Install cockpit
  apt:
    name: cockpit
    state: present

- name: cockpit - Set customized config
  template:
    src: "cockpit/cockpit.conf.j2"
    dest: "/etc/cockpit/cockpit.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  register: set_config

- name: cockpit - Set network dummy config
  template:
    src: "cockpit/10-globally-managed-devices.conf"
    dest: "/etc/NetworkManager/conf.d/10-globally-managed-devices.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  register: set_nw_config

- name: cockpit - apply network dummy config
  shell: "nmcli con add type dummy con-name fake ifname fake0 ip4 1.2.3.4/24 gw4 1.2.3.1"
  register: apply_nw_conf
  failed_when: apply_nw_conf.rc not in [0,1]
  when: set_nw_config.changed

- name: cockpit - Set systemd service
  systemd:
    name: "cockpit.socket"
    state: started
    enabled: true
  when: set_config.changed
