# docker Settings
---
- name: Docker - Install dependency packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Docker - Create directory
  ansible.builtin.file:
    path: "/etc/apt/keyrings"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Docker - Add Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    owner: "root"
    group: "root"
    mode: "0644"
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Docker - Get dpkg architecture
  ansible.builtin.command: dpkg --print-architecture
  register: docker_dpkg_arch
  changed_when: false
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Docker - Add the repository to Apt sources
  ansible.builtin.apt_repository:
    # noqa yaml[line-length]
    repo: "deb [arch={{ docker_dpkg_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
    state: present
    filename: docker
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Docker - Install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true
    state: present
  register: install_docker

- name: Docker - Set systemd service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  when: install_docker.changed
