# docker Settings
---
- name: Docker - Install dependency packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Docker - Create directory
  ansible.builtin.file:
    path: "/etc/apt/keyrings"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Docker - Add Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    owner: "root"
    group: "root"
    mode: "0644"
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Docker - Get dpkg architecture
  ansible.builtin.command: dpkg --print-architecture
  register: docker_dpkg_arch
  changed_when: false
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Docker - Add the repository to Apt sources
  ansible.builtin.copy:
    content: |
      Types: deb
      URIs: https://download.docker.com/linux/ubuntu
      Suites: {{ ansible_facts['distribution_release'] }}
      Components: stable
      Architectures: {{ docker_dpkg_arch.stdout }}
      Signed-By: /etc/apt/keyrings/docker.asc
    dest: /etc/apt/sources.list.d/docker.sources
    owner: root
    group: root
    mode: "0644"
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Docker - Install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Docker - Set systemd service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
