# docker Settings
---
- name: docker - Install dependency packages
  apt:
    name:
      - ca-certificates
      - curl
    state: present
  when: ansible_distribution == "Ubuntu"

- name: docker - Create directory
  file:
    path: "/etc/apt/keyrings"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  when: ansible_distribution == "Ubuntu"

- name: docker - Add Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    owner: "root"
    group: "root"
    mode: "0644"
  when: ansible_distribution == "Ubuntu"

- name: docker - Add the repository to Apt sources
  shell: |
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null
  register: docker_apt_add_repo
  changed_when: false
  failed_when: docker_apt_add_repo.rc != 0
  when: ansible_distribution == "Ubuntu"

- name: docker - Install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true
    state: present
  register: install_docker

- name: docker - Set systemd service
  systemd:
    name: docker
    state: started
    enabled: true
  when: install_docker.changed
