# Load balancer for mc.a-marsh.net

map $minecraft_server $minecraft_backend {
  "dev.mc.a-marsh.net"   oci-dev-sv01.a-marsh.net:25565;
  "mc.a-marsh.net"       kagoya-mc-sv01.a-marsh.net:25565;
  "edion.mc.a-marsh.net" kagoya-mc-edion-sv01.a-marsh.net:25565;

  # Unknown domains are rejected by proxying to a closed local port (ECONNREFUSED)
  default                127.0.0.1:1;
}

server {
  listen 25565;

  js_preread minecraft_router.preread;
  proxy_pass $minecraft_backend;
}
