map $minecraft_server $minecraft_backend {
  "dev.mc.a-marsh.net"   oci-dev-sv01.a-marsh.net:25565;
  "mc.a-marsh.net"       oci-mc-sv01.a-marsh.net:25565;
  "edion.mc.a-marsh.net" kagoya-mc-edion-sv01.a-marsh.net:25565;
  default                127.0.0.1:1;
}

server {
  listen 25565;
  js_preread minecraft_router.preread;
  proxy_pass $minecraft_backend;
  proxy_connect_timeout 5s;
  proxy_timeout 10m;
}
