# Stream proxy for pal.a-marsh.net

server {
  listen 8211 udp;

  set $backend_server kagoya-pal-sv01.a-marsh.net:8211;
  proxy_pass $backend_server;
}

server {
  listen 27015 udp;

  set $backend_server kagoya-pal-sv01.a-marsh.net:27015
  proxy_pass $backend_server;
}
