map $server_port $palworld_backend {
  8211  "kagoya-pal-sv01.a-marsh.net:8211";
  27015 "kagoya-pal-sv01.a-marsh.net:27015";
  default "kagoya-pal-sv01.a-marsh.net:8211";
}

server {
  listen 8211 udp;
  listen 27015 udp;
  proxy_pass $palworld_backend;
  proxy_connect_timeout 5s;
  proxy_timeout 10m;
}
