# Linux hostname Settings

# vars example
# vars:
#   hostname: string
---
- name: Hostname - Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  when: ansible_virtualization_type | default('') not in ['docker', 'lxc', 'podman', 'container']
