---
- ansible.builtin.import_tasks: hostname.yml
- ansible.builtin.import_tasks: timezone.yml
- ansible.builtin.import_tasks: sshd.yml
- ansible.builtin.import_tasks: sudo.yml
- ansible.builtin.import_tasks: users.yml
- ansible.builtin.import_tasks: apt.yml