# Linux sudo Settings
---
- name: Sudo - Install sudo
  ansible.builtin.apt:
    name: sudo
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Sudo - Create directory
  ansible.builtin.file:
    path: "/etc/sudoers.d"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"

- name: Sudo - Set customized config
  ansible.builtin.template:
    src: "sudoers.d/generated-ansible"
    dest: "/etc/sudoers.d/generated-ansible"
    owner: "root"
    group: "root"
    mode: "0440"
