# Linux timezone Settings

# vars example
# vars:
#   timezone: string
---
- name: Timezone - Check timezone
  ansible.builtin.command: timedatectl status
  register: system_current_timezone
  changed_when: false

- name: Timezone - Change timezone if changed
  ansible.builtin.command: timedatectl set-timezone Asia/Tokyo
  when: "'Asia/Tokyo' not in system_current_timezone.stdout"
