groups:
  - name: cloudflare
    rules:
      # Worker
      - alert: CfWorkerError
        expr: increase(cloudflare_worker_errors_count[1m]) > 0
        for: 0m
        labels:
          severity: critical
        annotations:
          title: "{% raw %}{{ $labels.script_name }}({{ $labels.status }}){% endraw %}"
          description: "{% raw %}Workers encountered an error.\nCurrent is {{ $value }}{% endraw %}"
