groups:
  - name: hosts
    rules:
      # Capacity
      - alert: HostDown
        expr: up{job="hosts"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          title: "{% raw %}{{ $labels.instance }}{% endraw %}"
          description: "Failed to scrape for more than 5 minutes."

      - alert: HostMemory
        expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "{% raw %}{{ $labels.instance }}{% endraw %}"
          description: "{% raw %}Memory is filling up (< 10% left).\nCurrent is {{ $value }}.{% endraw %}"

      - alert: HostSwap
        expr: (1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "{% raw %}{{ $labels.instance }}{% endraw %}"
          description: "{% raw %}Swap is filling up (< 10% left).\nCurrent is {{ $value }}{% endraw %}"

      - alert: HostCpuLoad
        expr: 100 - (avg by(instance, project) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "{% raw %}{{ $labels.instance }}{% endraw %}"
          description: "{% raw %}CPU load(5m) is high (> 80%).\nCurrent is {{ $value }}{% endraw %}"

      # Please add ignored mountpoints in node_exporter parameters like
      # "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|run)($|/)".
      # Same rule using "node_filesystem_free_bytes" will fire when disk fills for non-root users.
      - alert: HostDiskSpace
        expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "{% raw %}{{ $labels.instance }}({{ $labels.mountpoint }}){% endraw %}"
          description: "{% raw %}Disk is almost full (< 10% left).\nCurrent is {{ $value }}{% endraw %}"

      - alert: HostDiskInode
        expr: node_filesystem_files_free{mountpoint="/rootfs"} / node_filesystem_files{mountpoint="/rootfs"} * 100 < 10 and ON (instance, device, mountpoint) node_filesystem_readonly{mountpoint="/rootfs"} == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "{% raw %}{{ $labels.instance }}{% endraw %}"
          description: "{% raw %}Disk is almost running out of available inodes (< 10% left).\nCurrent is {{ $value }}{% endraw %}"

      - alert: HostOOM
        expr: increase(node_vmstat_oom_kill[1m]) > 0
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "{% raw %}{{ $labels.instance }}{% endraw %}"
          description: "{% raw %}OOM kill detected.\nCurrent is {{ $value }}{% endraw %}"

      - alert: HostSyncClock
        expr: min_over_time(node_timex_sync_status[1m]) == 0 and node_timex_maxerror_seconds >= 16
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "{% raw %}{{ $labels.instance }}{% endraw %}"
          description: "{% raw %}Clock not synchronising.\nCurrent is {{ $value }}{% endraw %}"

      # App
      - alert: AppSystemdStatus
        expr: node_systemd_unit_state{project="obs",name="observability.service",state="active"} == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          title: "{% raw %}{{ $labels.instance }}{% endraw %}"
          description: "{% raw %}Failed to run {{ $labels.name }}.{% endraw %}"

      - alert: AppSystemdStatus
        expr: node_systemd_unit_state{project="obs",name="uptime-kuma.service",state="active"} == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          title: "{% raw %}{{ $labels.instance }}{% endraw %}"
          description: "{% raw %}Failed to run {{ $labels.name }}.{% endraw %}"

      - alert: AppSystemdStatus
        expr: node_systemd_unit_state{project="rpx",name="nginx.service",state="active"} == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          title: "{% raw %}{{ $labels.instance }}{% endraw %}"
          description: "{% raw %}Failed to run {{ $labels.name }}.{% endraw %}"

      - alert: AppSystemdStatus
        expr: node_systemd_unit_state{project="mc",name="minecraft.service",state="active"} == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          title: "{% raw %}{{ $labels.instance }}{% endraw %}"
          description: "{% raw %}Failed to run {{ $labels.name }}.{% endraw %}"

      - alert: AppSystemdStatus
        expr: node_systemd_unit_state{project="pal",name="palworld.service",state="active"} == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          title: "{% raw %}{{ $labels.instance }}{% endraw %}"
          description: "{% raw %}Failed to run {{ $labels.name }}.{% endraw %}"
