groups:
  - name: alerts_hosts
    rules:
      - alert: Node down
        expr: up == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          title: "{% raw %}Node {{ $labels.instance }} is down{% endraw %}"
          description: "{% raw %}Failed to scrape {{ $labels.job }} on {{ $labels.instance }} for more than 2 minutes. Node seems down.{% endraw %}"
