groups:
  - name: nginx
    rules:
      - alert: NginxDown
        expr: nginx_up{job="nginx"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          description: "Failed to scrape for more than 5 minutes."
