groups:
  - name: nginx
    rules:
      - alert: NginxDown
        expr: nginx_up{project="rpx"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          description: "Failed to scrape for more than 5 minutes."
