services:
  app:
    image: nginx:1.30.0
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/minecraft_router.js:/etc/nginx/minecraft_router.js:ro
      - ./data/log:/var/log/nginx
      - /etc/timezone:/etc/timezone:ro
    network_mode: host
    pid: host
    restart: always

  exporter:
    image: nginx/nginx-prometheus-exporter:1.5.1
    command:
      - --nginx.scrape-uri=http://localhost:8080/stub_status
    volumes:
      - /etc/timezone:/etc/timezone:ro
    network_mode: host
    restart: always
    depends_on:
      - app
