# app Settings (uptime-kuma)

# vars example
# vars:
#   kuma_cloudflared_token: string
---
- name: kuma - Create directory
  file:
    path: "/opt/a-marsh/kuma"
    state: directory
    owner: "am-helper"
    group: "am-helper"
    mode: "0755"

- name: kuma - Create docker compose config
  template:
    src: "compose.yaml"
    dest: "/opt/a-marsh/kuma/compose.yaml"
    owner: "am-helper"
    group: "am-helper"
    mode: "0644"
  register: set_docker_config

- name: kuma - Create systemd service
  template:
    src: "uptime-kuma.service"
    dest: "/etc/systemd/system/uptime-kuma.service"
    owner: "am-helper"
    group: "am-helper"
    mode: "0644"
  register: set_systemd_config

- name: kuma - Restart systemd service if changed
  systemd:
    name: "uptime-kuma.service"
    daemon-reload: true
    state: restarted
    enabled: true
  ignore_errors: true
  when: set_docker_config.changed or set_systemd_config.changed
