---
- name: Am-helper - Copy config
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/host_vars/localhost"
    dest: "/opt/a-marsh/am-helper/ansible/host_vars/localhost"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Am-helper - Reload systemd service
  ansible.builtin.systemd:
    name: "{{ item }}"
    daemon_reload: true
    state: restarted
    enabled: true
  with_items:
    - "am-helper.service"
    - "am-helper.timer"
