---
- name: Am-helper - Copy config
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/host_vars/localhost"
    dest: "/opt/a-marsh/am-helper/ansible/host_vars/localhost"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Am-helper - Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Am-helper - Enable am-helper service
  ansible.builtin.systemd:
    name: "am-helper.service"
    enabled: true

- name: Am-helper - Enable and start am-helper timer
  ansible.builtin.systemd:
    name: "am-helper.timer"
    enabled: true
    state: started
