# app Settings (observability)

# vars example
# vars:
#  o11y_cloudflared_token: string
#  o11y_prom_client_secret_token: string
#  o11y_prom_kuma_api_key: string
#  o11y_alertmanager_username: string
#  o11y_alertmanager_password: string
#  o11y_exporter_cloudflare_cf_accounts: string
#  o11y_exporter_cloudflare_cf_api_token: string
---
- name: O11y - Create directory
  ansible.builtin.file:
    path: "/opt/a-marsh/observability"
    state: directory
    owner: "am-helper"
    group: "am-helper"
    mode: "0755"

- name: O11y - Create config directory
  ansible.builtin.file:
    path: "/opt/a-marsh/observability/{{ item.path }}"
    state: directory
    owner: "am-helper"
    group: "am-helper"
    mode: "0755"
  with_filetree: "templates/"
  when: item.state == "directory"

- name: O11y - Create config
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/opt/a-marsh/observability/{{ item.path | regex_replace('\\.j2$', '') }}"
    owner: "am-helper"
    group: "am-helper"
    mode: "0644"
  register: set_docker_config
  with_filetree: "templates/"
  when: item.state == "file"

- name: O11y - Create systemd service
  ansible.builtin.template:
    src: "observability.service"
    dest: "/etc/systemd/system/observability.service"
    owner: "am-helper"
    group: "am-helper"
    mode: "0644"
  register: set_systemd_config

- name: O11y - Restart systemd service if changed
  ansible.builtin.systemd:
    name: "observability.service"
    daemon-reload: true
    state: restarted
    enabled: true
  ignore_errors: true
  when: set_docker_config.changed or set_systemd_config.changed
