route:
  receiver: default
  group_by: ["alertname", "job", "instance"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1d
  routes:
    - receiver: discord
      match_re:
        severity: "warning|critical"

receivers:
  - name: default
  - name: discord
    discord_configs:
      - webhook_url: "{{ alertmanager_discord_webhook_url }}"
        title: >-
          {% raw %}{{ if .CommonLabels.project }}[{{ .CommonLabels.project }}]{{ end }} [{{ .CommonAnnotations.summary }}] {{ if .CommonAnnotations.title }}{{ .CommonAnnotations.title }}{{ end }} ({{ .CommonLabels.severity }}){% endraw %}
        message: |
          {% raw %}{{ range .Alerts -}}
          {{ .Annotations.description }}

          Source: {{ .GeneratorURL }}
          {{ end }}{% endraw %}
