---
- name: Unique-oci - Install iptables
  ansible.builtin.apt:
    name:
      - iptables-persistent
      - netfilter-persistent
    state: present
  become: true
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Unique-oci - Set iptables rules
  ansible.builtin.template:
    src: rules.v4.j2
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: "0640"
  become: true
  notify:
    - "Unique-oci - Apply iptables rules"
