---
- hosts: localhost
  roles:
    - role: system
      tags: system
    - role: common-apps
      tags: common-apps
    - role: ops
      tags: ops

    - role: o11y
      tags: o11y
      when: (o11y_prom_client_secret_token is defined) and (o11y_prom_kuma_api_key is
        defined) and (o11y_cloudflared_token is defined) and
        (o11y_alertmanager_username is defined) and (o11y_alertmanager_password
        is defined)
    - role: uptime-kuma
      tags: uptime-kuma
      when: kuma_cloudflared_token is defined
    - role: nginx
      tags: nginx
      when: nginx_running is defined
    - role: minecraft
      tags: minecraft
      when: mc_version is defined
    - role: palworld
      tags: palworld
      when: (pal_join_fqdn is defined) and (pal_discord_webhook_url is defined) and
        (pal_server_password is defined) and (pal_admin_password is defined)
