split_clients $request_id $prometheus_upstream {
  50%  "prometheus-01.a-marsh.net";
  *    "prometheus-02.a-marsh.net";
}

server {
  listen 80;
  server_name prometheus.a-marsh.net;

  location / {
    proxy_pass https://$prometheus_upstream;
    proxy_ssl_server_name on;
    proxy_ssl_name $prometheus_upstream;

    proxy_set_header Host                    $prometheus_upstream;
    proxy_set_header CF-Access-Client-Id     "8d91f52eb1bf485189d0525137105827.access";
    proxy_set_header CF-Access-Client-Secret "{{ rpx_client_secret_token }}";

    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_http_version 1.1;
    proxy_set_header   Connection "";

    proxy_connect_timeout 10s;
    proxy_read_timeout    60s;
    proxy_send_timeout    60s;
  }
}
