name: Ansible CI (Check)

on:
  pull_request:
    branches:
      - develop
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read
  pull-requests: write

jobs:
  check-lint:
    uses: ./.github/workflows/_ansible-run-output.yml
    with:
      comment-heading: Ansible Check (Lint)
      output-file: ansible-lint.txt
      run-cmd: ansible-lint ansible/main.yml 2>&1 | tee ansible-lint.txt

  check-syntax:
    uses: ./.github/workflows/_ansible-run-output.yml
    with:
      comment-heading: Ansible Check (Syntax)
      output-file: ansible-check.txt
      run-cmd: ansible-playbook ansible/main.yml --syntax-check 2>&1 | tee ansible-check.txt

  # check-plan:
  #   uses: ./.github/workflows/_ansible-run-output.yml
  #   with:
  #     comment-heading: Ansible Plan
  #     output-file: ansible-plan.txt
  #     fetch-depth: 0
  #     run-cmd: ansible-playbook ansible/main.yml --become --check --diff 2>&1 | tee ansible-plan.txt